### ISSUE TITLE
Missing language tab.

### ISSUE THREAD

**Issue by r2690698** [aws-scripting-guy/cform-VSCode#1]
The language UI element stops working for JSON (is missing). 

Workaround to change the language when in file.  

cmd+SHIFT+P  > Change Language Mode

![image](https://cloud.githubusercontent.com/assets/16682510/12547443/679a0344-c348-11e5-96f7-b879a7983cf3.png)

**Comment by aws-scripting-guy** [comment]
Fixed https://github.com/aws-scripting-guy/cform-VSCode/commit/de88c31cf4af8225e17aea688f213ad8693d2002

For fast Language Mode change you can also use Ctrl+K M and then select desired language.
