### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by bence-takacs** [aws-scripting-guy/cform-VSCode#10]
After following the proxy instructions ([](https://github.com/aws-scripting-guy/cform-VSCode#troubleshooting)) I still get the following:

```
Settings have been updated...
Settings: {"cfnLint":{"path":"cfn-lint","appendRules":[],"ignoreRules":[],"overrideSpecPath":""}}
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: spawn cfn-lint ENOENT
    at exports._errnoException (util.js:1050:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
Is CFN: true
[Info  - 1:42:03 PM] Connection to server got closed. Server will restart.
```

So: where should I enter the proxy url and certificates?
(env variables: **http_proxy**, **https_proxy** and **cafile** are all set)

**Comment by aws-scripting-guy** [comment]
Hi, do you still have issues behind the proxy? If yes, can you elaborate more on details what you are trying to accomplish?

**Comment by aws-scripting-guy** [comment]
Closing this issue, please reopen if there's still an issue.
