### ISSUE TITLE
YAML for ec2-instance Properties UserData generates an error when launching stack

### ISSUE THREAD

**Issue by charles545587** [aws-scripting-guy/cform-VSCode#15]
The template for an ec2-instance produces a property of Userdata.

This generates an error when trying to launch the stack.  This is due to the official documentation for this property in YAML being case sensitive camel case.  This should be UserData not Userdata.

This was tested by manually amending the template to UserData and the stack launched without error.

I confirmed the correct syntax using the Official documentation: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html

**Comment by darko-mesaros** [comment]
I can confirm the same issue.

**Comment by charles545587** [comment]
In the end I have downloaded as a zip and manually installed so that I can correct errors and update the resources as I go.  Instructions on how to do this are on the VS Code website.

**Comment by aws-scripting-guy** [comment]
Should be resolved now.
