### ISSUE TITLE
highlighting correct syntax as incorrect. 

### ISSUE THREAD

**Issue by r2690698** [aws-scripting-guy/cform-VSCode#2]
';' expected 
Declaration or statement expected  

Only happens in 1 file so far (has .JSON extension) 

![image](https://cloud.githubusercontent.com/assets/16682510/12547536/00a8a66c-c349-11e5-8616-62d2855e8176.png)

**Comment by aws-scripting-guy** [comment]
Please try with newest version. If that happens again post JSON body.

**Comment by r2690698** [comment]
this has been resolved in new build, sorry for the late update.
