### ISSUE TITLE
YAML Support

### ISSUE THREAD

**Issue by johnmckinzie** [aws-scripting-guy/cform-VSCode#3]
Add support for new CloudFormation YAML templates.

https://aws.amazon.com/about-aws/whats-new/2016/09/aws-cloudformation-introduces-yaml-template-support-and-cross-stack-references/

**Comment by timzuiddam** [comment]
+1

**Comment by aws-scripting-guy** [comment]
Hi there. Looking into transformation options.

**Comment by Pitta** [comment]
Hows this coming?

**Comment by reidca** [comment]
I would love to see YAML support. I do all my cloudformation in YAML these days so unfortunately this tool is not much use to me.

It also seems to me that the majority of sample templates provided by AWS these days come in YAML and it appears to be the primary format from what I can see so it would make much sense to add YAML support.

**Comment by xBytez** [comment]
I recently made the switch from JSON to YAML too for CFM. I'd love to see YAML support as well.

**Comment by andrewhharmon** [comment]
+1

**Comment by Marakai** [comment]
I'll throw in my +1 for YAML support as I don't really want to go back to JSON.

However, with the last commit a year old and a PR still open from Dec 2017 I wonder if this is still alive at all?

**Comment by aws-scripting-guy** [comment]
Yep I am still alive :)

YAML snippet support didn't worked well pre-2018. Now I tested it out with [YAML language support from Red hat ](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml)and it works flawlessly.

Check out **test** YAML support in release 0.0.11. Syntax is the same - `start `to populate basic template, in the time of the writing there's only `vpc` and `tag` resource available through YAML snippet. I'll need to rewrite all of the snippets (manually) so please check out new releases for full support.

**Comment by rhbecker** [comment]
I can't seem to get this to work.

1. Installed v0.0.12.
2. Restarted vs code.
3. Created new file.
4. Set language mode to YAML.
5. Typed `start` and hit `tab`.

... nothing happens. Following the same steps, but using JSON for step 4 works fine.

**Comment by aws-scripting-guy** [comment]
Do you have YAML language server installed? E.g. [redhat.vscode-yaml](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml)

**Comment by rhbecker** [comment]
I did not (didn't read your post closely enough to realize I had to install a dependency), but now I do and it's working. Thanks!

**Comment by aws-scripting-guy** [comment]
Thank you for confirming. I will add this step in the README.

**Comment by iDVB** [comment]
I had this all working previously but suddenly it stopped working for YAML only.
JSON works but typing `start` in a yaml template does nothing.

I have this plugin installed. https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml
and I can confirm it seems to be working.

**Comment by sabumike** [comment]
Please let me know when to expect YAML support on VSCode. It does not seem to work.
